name: tekartik_google_jsapi
version: 0.2.1
description: js api loader
publish_to: none
environment:
  sdk: ^3.8.0
dependencies:
  web:
  tekartik_browser_utils:
    git:
      url: https://github.com/tekartik/browser_utils.dart
      ref: dart3a
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a

dev_dependencies:
  http:
  yaml: ">=3.1.2"
  dev_build: ">=1.1.2"
  tekartik_bootstrap:
    git:
      url: https://github.com/tekartik/bootstrap.dart
      ref: dart3a
    version: '>=0.3.0'
  test: ">=1.24.0"
  build_runner: ">=2.4.13"
  build_web_compilers: ">=4.0.11"
  build_test:
  process_run: ">=1.2.1+1"

dependency_overrides:
  web: ">=1.1.0"
