name: tekartik_google_jsapi
version: 0.2.0
description: js api loader

environment:
  sdk: '>=2.4.0-dev <3.0.0'
dependencies:
  tekartik_browser_utils:
    git:
      url: git://github.com/tekartik/browser_utils.dart
      ref: dart2
    version: '>=0.1.0'

dev_dependencies:
  tekartik_bootstrap:
    git:
      url: git://github.com/tekartik/bootstrap.dart
      ref: dart2
    version: '>=0.3.0'
  test: any
  build_runner:
  build_web_compilers:
  build_test:
  process_run: '>=0.10.2'


