name: tekartik_google_jsapi
version: 0.1.0
description: js api loader
dependencies:
  browser: any
  tekartik_utils:
    git: git://github.com/alextekartik/tekartik_utils.dart
dev_dependencies:
  bootstrap: any
  test: any


