name: tekartik_google_jsapi
version: 0.2.1
description: js api loader
publish_to: none
environment:
  sdk: ^3.5.0
dependencies:
  tekartik_browser_utils:
    git:
      url: https://github.com/tekartik/browser_utils.dart
      ref: dart3a
    version: '>=0.1.0'

dev_dependencies:
  http:
  yaml:
  dev_build:
  tekartik_bootstrap:
    git:
      url: https://github.com/tekartik/bootstrap.dart
      ref: dart3a
    version: '>=0.3.0'
  test: any
  build_runner:
  build_web_compilers:
  build_test:
  process_run: '>=0.10.2'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
